### ISSUE TITLE
IOS IPv6 rules

### ISSUE THREAD

**Issue by nickrusso42518** [nickrusso42518/stig#1]
Implement (experiment with) IPv6 rule checks based on the template now. It may not work.

```
---
severity: x
desc: whatever
check:
  text: whatever
  text_cnt: x
  parent: interface, acl, etc
  when: ipv6\s+unicast-routing (global) or ipv6\s+address (interface)
part_of_stig:
  - l3pr
  - l3ps
...
```
