### ISSUE TITLE
IOS N/A rules

### ISSUE THREAD

**Issue by nickrusso42518** [nickrusso42518/stig#2]
Identify rules that are N/A or manual-only and create placeholder files for a more complete checklist.

```
---
severity: 2
desc: N/A test
check:
  text: bogustext
  text_cnt: 1
  parent: call-home
  when: bogustext
part_of_stig:
  - fw
...
```
